### ISSUE TITLE
Could make // into comments for JSON ?

### ISSUE THREAD

**Issue by agsb** [guettli/lets-fix-js#1]
Leave comments is essential for human beings understand what is going up.
Is the best practice in any programming language.
Is kind and nice for all who will study what is done.
Every one knows that JSON was, -was- a encapsuled internal way to exchange data in javascript
but now JSON is used do describe the data for all world.
So, please make // into comments for JSON, let the spice flow.

**Comment by guettli** [comment]
Thank you very much for your feedback. I added it to the list. Please let me know if you have further ideas.
